# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Continuous Integration

on: pull_request

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
      # Just doing this to speed it up
      # - run: yarn prettier-check
      # - run: yarn lint
      # - run: yarn test
      - run: mkdir artifacts
      - run: yarn pack --filename artifacts/datadog-ci.tgz
      - run: cp -r .github/workflows/e2e artifacts/
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts/

  e2e-test:
    name: End-to-end test the package
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/download-artifact@v1
        with:
          name: artifacts
      - run: yarn add ./artifacts/datadog-ci.tgz
      # - name: Run synthetics test
      #   run: yarn datadog-ci synthetics run-tests --config artifacts/e2e/global.config.json
      #   env:
      #     DATADOG_API_KEY: ${{ secrets.datadog_api_key }}
      #     DATADOG_APP_KEY: ${{ secrets.datadog_app_key }}
      - name: Run wrapper command
        run: yarn datadog-ci trace command ls -r
      - name: Run wrapper command with error
        run: yarn datadog-ci trace command ls -ee

  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn check-licenses
