# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Continuous Integration

on: pull_request

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      agent:
        image: store/datadog/agent:6.11.3
        env:
          DD_API_KEY: ${{ secrets.datadog_api_key }}
          DD_ENV: testing-juan
          DD_APM_ENABLED: true
        ports:
          - 8126:8126

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
      - run: yarn prettier-check
      - run: yarn lint
      - run: yarn test
        env:
          DD_SERVICE: datadog-ci-tests
      - run: mkdir artifacts
      - run: yarn pack --filename artifacts/datadog-ci.tgz
      - run: cp -r .github/workflows/e2e artifacts/
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts/

  e2e-test:
    name: End-to-end test the package
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/download-artifact@v1
        with:
          name: artifacts
      - run: yarn add ./artifacts/datadog-ci.tgz
      - name: Run synthetics test
        run: yarn datadog-ci synthetics run-tests --config artifacts/e2e/global.config.json
        env:
          DATADOG_API_KEY: ${{ secrets.datadog_api_key }}
          DATADOG_APP_KEY: ${{ secrets.datadog_app_key }}
      - name: Run dependencies upload test
        run: yarn datadog-ci dependencies upload artifacts/e2e/test.dependencies.json --source=snyk --service=my-service --release-version=1.23.4
        env:
          DATADOG_API_KEY: ${{ secrets.datadog_api_key }}
          DATADOG_APP_KEY: ${{ secrets.datadog_app_key }}

  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn check-licenses
